# We can use "*" a wildcard to expose all the endpoints otherwise comma-delimited is also usable


# management.endpoints.web.exposure.include=health,info

management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.exclude=beans
management.info.env.enabled=true
spring.application.name=DayOne

info.app.name= IamManishPandey
info.app.description= This is Manish Pandey
info.app.version = 1.0

spring.security.user.name=Manish
spring.security.user.password=8987
